export { default as productsReducer } from './productsReducer' 
export { default as categoryReducer } from './categoryReducer'
export {default as cartReducer } from './cartReducer'
export {default as ordersReducer} from './ordersReducer'
export {default as authReducer} from './authReducer'